name: EmpireCommandSigns
main: clusidc.EmpireCommandSigns.EmpireCommandSigns
version: Beta-0.4-dev-1
softdepend: [Vault]
commands:
  ecs:
    description: EmpireCommandSigns http://dev.bukkit.org/server-mods/empirecommandsigns/