name: EmpireCommandSigns
main: clusidc.EmpireCommandSigns.EmpireCommandSigns
version: Beta-0.4c
softdepend: [Vault]
depend: [SQLibrary]
commands:
  ecs:
    description: EmpireCommandSigns http://dev.bukkit.org/server-mods/empirecommandsigns/