name: EmpireCommandSigns
main: clusidc.EmpireCommandSigns.EmpireCommandSigns
version: Beta-0.3.1
commands:
  ecs:
    description: Plugin EmpireCommandSigns http://dev.bukkit.org/server-mods/empirecommandsigns/